/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* Real values must be set via environment variables VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY */

export const projectId = import.meta.env.VITE_SUPABASE_URL?.match(/https:\/\/([^.]+)\./)?.[1] ?? ""
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? ""
